### ISSUE TITLE
进度条绘制时的起点不是在进度条的最左边

### ISSUE THREAD

**Issue by carrys17** [shonnybing/SpeedProgressBar#2]
进度条绘制时的起点不是在进度条的最左边，而是在屏幕外面开始画进来，将进度条高度调大点，效果更加明显

**Comment by shonnybing** [comment]
感谢指出，已修复~

**Comment by Johnnycxq** [comment]
大佬，改动的地方有注明吗？

**Comment by carrys17** [comment]
@Johnnycxq 在LevelProgressBar 的绘制进度条那里，加多了一个判断，165行开始

**Comment by shonnybing** [comment]
@Johnnycxq 可以看commit记录哈
